# Generated by Django 4.1.5 on 2023-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_blog', '0002_game_rating_game_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
    ]
