# Generated by Django 4.1.3 on 2023-01-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_blog', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Action-Adventure', 'Action-Adventure'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Role-Playing', 'Role-Playing'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('MMO', 'MMO')], default='Action', max_length=50),
        ),
    ]
